#!/usr/bin/env ruby

require 'highline/import'
Dir["./app/**/*.rb"].each { |file| require file }
Dir["./lib/*.rb"].each { |file| require file }

menu_prompt = "1. Create New Game\n2. Open Existing Game\n3. Quit\n"
secondary_menu = "1. Add room\n2. Add Object\n3. Edit Room\n4. Edit Object\n5. Quit\n"
input = ARGV


if input.size == 1 and input[0] == 'start'
  choose do |menu|
    menu.prompt = ""
    menu.choice('Create New Game') {
      puts "Welcome to Textula!\n"
      puts "The Textula game engine will now walk you through creating your own text-adventure game!\n"
      puts "So lets get started!\n"
      game = GamesController.new
      game.create
      loop do
        choose do |menu|
          menu.prompt = ""
          menu.choice('Add room') {
            puts "Welcome to the room creator!\n"
            rooms = RoomsController.new
            rooms.start(game.game_id)
          }
          menu.choice('Add object') {
            puts "so you want to add an object?"
          }
          menu.choice('Edit room') {
            puts "so you want to edit a room?"
          }
          menu.choice('Edit object') {
            puts "so you want to edit an object?"
          }
          menu.choice('Play game') {
            game.play
          }
          menu.choice('Quit') {
            puts "Thanks for playing!\n"
            exit
          }
        end
      end
    }
    menu.choice('Edit Existing Game') {
      loop do
        choose do |menu|
          menu.prompt = ""
          menu.choice('Add room') {
            puts "Welcome to the room creator!\n"
            rooms = RoomsController.new
            rooms.start
          }
          menu.choice('Add object') {
            puts "so you want to add an object?"
          }
          menu.choice('Edit room') {
            puts "so you want to edit a room?"
          }
          menu.choice('Edit object') {
            puts "so you want to edit an object?"
          }
          menu.choice('Play game') {
            puts "this plays the current game!"
          }
          menu.choice('Quit') {
            puts "Thanks for playing!"
            exit
          }
        end
      end
    }
    menu.choice('Play Saved Game') {
      puts "this finds all available games and lets you pick which ones to play!"
    }
    menu.choice('Quit') { puts "Thanks for playing!\n" }
  end
else
  puts "[Help] Run as: ./textula start\n"
end
